from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage  # Added missing imports
from src.agents.thinker.state import ThinkerState
from src.shared.client import SELECTOR_CLIENT as llm
from src.agents.thinker.prompts import SELECTOR_SYSTEM_PROMPT as system_prompt
from src.shared.utils.general_utils import clean_docstring
from typing import List
from pydantic import BaseModel


# 1. You must define this so the LLM knows the structure to return
class ScorerOutput(BaseModel):
    weights: List[float]


def comparator(state: ThinkerState):
    """
    Sorts candidates generated by the brainstormer, and decides if we have an idea worth testing.
    An empty output means "no good ideas, keep brainstorming".
    """
    if not state.candidate_ideas:
        return {"candidate_ideas": []}

    ranked = sorted(
        state.candidate_ideas,
        key=lambda x: x.p_success * (1 - x.p_local_minima),
        reverse=True
    )

    user_prompt = clean_docstring(f"""
    <Goal>
    {state.problem_statement}
    </Goal>
    <Current Code>
    {state.current_code}
    </Current Code>
    <Ideas>
    {[x.concept for x in ranked]}
    </Ideas>
    """)

    structured_llm = llm.with_structured_output(ScorerOutput)

    response = structured_llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ])

    for i, weight in enumerate(response.weights):
        if i < len(ranked):
            ranked[i].p_success *= weight
            ranked[i].p_success *= 1 - ranked[i].p_local_minima
            ranked[i].p_success = max(0, min(1, ranked[i].p_success))
            ranked[i].p_success = ranked[i].p_success ** (1/3)

    ranked.sort(key=lambda x: x.p_success, reverse=True)

    best = ranked[0]

    # Return full list if the best is promising, else reset to keep brainstorming
    if best.p_success > 0.4:
        return {"candidate_ideas": ranked}

    return {"candidate_ideas": []}