from langchain_core.prompts import ChatPromptTemplate
from src.agents.thinker.state import ThinkerState

def comparator(state: ThinkerState):
    """
    Sorts candidates generated by the brainstormer, and if we have an idea worth testing.

    And empty output means "no good ideas, keep brainstorming".
    """
    if not state.candidate_ideas:
        return {"candidate_ideas": []}

    # Rank by Expected Value: p_success * (1 - p_local_minima)
    ranked = sorted(
        state.candidate_ideas,
        key=lambda x: x.p_success * (1 - x.p_local_minima),
        reverse=True
    )
    
    best = ranked[0]
    
    if best.p_success > 0.4:
        return {"candidate_ideas": ranked} 
    
    return {"candidate_ideas": []}